/*
 * generated by Xtext 2.24.0
 */
package dk.sdu.mmmi.mdsd

import org.eclipse.xtext.resource.IDefaultResourceDescriptionStrategy

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DialogFlowRuntimeModule extends AbstractDialogFlowRuntimeModule {
	
	 def Class<? extends IDefaultResourceDescriptionStrategy> bindIDefaultResourceDescriptionStrategy() {
	 	DialogFlowResourceDescriptionStrategy
	 }
}
